# Generated by Django 5.2.17 on 2026-09-01 15:01

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("eyebrow", models.CharField(blank=True, default="", max_length=200)),
                ("headline", models.CharField(blank=True, default="", max_length=300)),
                ("subheading", models.CharField(blank=True, default="", max_length=500)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, default="", upload_to=apps.content.models.hero_photo_upload_path
                    ),
                ),
                ("cv_url", models.URLField(blank=True, default="")),
                ("github_url", models.URLField(blank=True, default="")),
                ("linkedin_url", models.URLField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Hero section",
                "verbose_name_plural": "Hero section",
            },
        ),
    ]
