# Generated by Django 5.2.17 on 2026-09-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_brandsection"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("caption", models.CharField(blank=True, default="", max_length=100)),
                ("heading", models.CharField(blank=True, default="", max_length=300)),
                ("body", models.TextField(blank=True, default="")),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
            ],
            options={
                "verbose_name": "Contact section",
                "verbose_name_plural": "Contact section",
            },
        ),
    ]
