# Generated by Django 5.2.17 on 2026-09-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_contactsection"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperienceSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("heading", models.CharField(blank=True, default="", max_length=300)),
                ("body", models.TextField(blank=True, default="")),
                ("experiences", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Experience section",
                "verbose_name_plural": "Experience section",
            },
        ),
    ]
