# Generated by Django 5.2.17 on 2026-09-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_experiencesection"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectsSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("heading", models.CharField(blank=True, default="", max_length=300)),
            ],
            options={
                "verbose_name": "Projects section",
                "verbose_name_plural": "Projects section",
            },
        ),
    ]
