# Generated by Django 5.2.17 on 2026-09-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_projectssection"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunFactsSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("heading", models.CharField(blank=True, default="", max_length=300)),
                ("stats", models.JSONField(blank=True, default=list)),
                ("testimonials", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Fun facts section",
                "verbose_name_plural": "Fun facts section",
            },
        ),
    ]
