# Generated by Django 5.2.17 on 2026-09-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_funfactssection"),
    ]

    operations = [
        migrations.CreateModel(
            name="TickerSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phrases", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Ticker section",
                "verbose_name_plural": "Ticker section",
            },
        ),
    ]
