# Generated by Django 5.2.17 on 2026-09-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_tickersection"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("heading", models.CharField(blank=True, default="", max_length=200)),
                ("body", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "About section",
                "verbose_name_plural": "About section",
            },
        ),
    ]
