# Generated by Django 5.2.17 on 2026-09-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_aboutsection"),
    ]

    operations = [
        migrations.CreateModel(
            name="StackSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("languages", models.JSONField(blank=True, default=list)),
                ("data", models.JSONField(blank=True, default=list)),
                ("infra", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Stack section",
                "verbose_name_plural": "Stack section",
            },
        ),
    ]
