# Generated by Django 5.2.17 on 2026-09-04 19:02

import mimetypes
from pathlib import Path

from django.conf import settings
from django.db import migrations, models


def backfill_photo_from_disk(apps, schema_editor):
    """One-time move of the existing media/hero/photo.png bytes into the DB,
    since disk storage doesn't survive a Render redeploy anyway."""
    if not settings.MEDIA_ROOT:
        return
    HeroSection = apps.get_model("content", "HeroSection")
    path = Path(settings.MEDIA_ROOT) / "hero" / "photo.png"
    if not path.exists():
        return
    content_type, _ = mimetypes.guess_type(path.name)
    obj, _ = HeroSection.objects.get_or_create(pk=1)
    obj.photo_data = path.read_bytes()
    obj.photo_content_type = content_type or "image/png"
    obj.photo_filename = path.name
    obj.save()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_technology_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="herosection",
            name="photo",
        ),
        migrations.AddField(
            model_name="herosection",
            name="photo_content_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="herosection",
            name="photo_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="herosection",
            name="photo_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(backfill_photo_from_disk, noop_reverse),
    ]
