# Generated by Django 5.2.17 on 2026-09-01 15:08

import apps.case_studies.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("category", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=200)),
                ("detail_title", models.CharField(blank=True, default="", max_length=200)),
                ("budget", models.CharField(blank=True, default="", max_length=50)),
                ("client", models.CharField(blank=True, default="", max_length=100)),
                ("tool", models.CharField(blank=True, default="", max_length=100)),
                ("featured", models.BooleanField(default=False)),
                (
                    "banner",
                    models.ImageField(upload_to=apps.case_studies.models.case_study_upload_path),
                ),
                ("gallery", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["-date"], name="case_studie_date_99ceeb_idx"),
                    models.Index(fields=["featured"], name="case_studie_feature_d98635_idx"),
                    models.Index(fields=["slug"], name="case_studie_slug_2898e2_idx"),
                ],
            },
        ),
    ]
