# Generated by Django 5.2.17 on 2026-09-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_studies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="casestudy",
            options={"ordering": ["-date", "-created_at"], "verbose_name_plural": "case studies"},
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="budget",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="category",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="client",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="detail_title",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="gallery",
        ),
        migrations.RemoveField(
            model_name="casestudy",
            name="tool",
        ),
        migrations.AddField(
            model_name="casestudy",
            name="architecture",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="my_role",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="outcome",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="problem",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="source_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="casestudy",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
