# Generated by Django 5.2.17 on 2026-09-02 12:02

import apps.case_studies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_studies", "0002_alter_casestudy_options_remove_casestudy_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestudy",
            name="banner",
            field=models.ImageField(
                blank=True, default="", upload_to=apps.case_studies.models.case_study_upload_path
            ),
        ),
    ]
